### ISSUE TITLE
problem in /general/train/connect_loss.py

### ISSUE THREAD

**Issue by ZejunHe** [Zyun-Y/BiconNets#3]
This file code has errors, starting from line 96, hope you can fix as soon as possible, thank you very much！！！！

**Comment by Zyun-Y** [comment]
Hi,

We apologize for this. This could be due to the frequent updates of the codes. We are working on updating the code and will make everything clear in two days.

**Comment by Zyun-Y** [comment]
> This file code has errors, starting from line 96, hope you can fix as soon as possible, thank you very much！！！！

Hi,

We just had a thorough check of the codes and realized the codes were messed up due to the uncareful updates we made before.

We have updated the entire repository and it passed our test. The codes are now fixed and should be able to run directly. Please let us know if you find any other issues. Thank you again for your interest and patience. We apologize for any inconvenience.
